In [1]:
import pandas as pd
import numpy as np

## Worklist prioritization: Emergency Setting

In [2]:
## First, read in the file of the current worklist with the probabilities that your two algorithms have
## generated for the two types of findings you're most concerned with:

worklist = pd.read_csv('probabilities.csv')

In [3]:
worklist.head()

   Image_Type  Brain_bleed_probability  Aortic_dissection_probability
0  chest_xray                      0.0                           0.05
1  chest_xray                      0.0                           0.17
2  chest_xray                      0.0                           0.00
3  chest_xray                      0.0                           0.04
4  wrist_xray                      0.0                           0.00

In [4]:
worklist

    Image_Type  Brain_bleed_probability  Aortic_dissection_probability
0   chest_xray                     0.00                           0.05
1   chest_xray                     0.00                           0.17
2   chest_xray                     0.00                           0.00
3   chest_xray                     0.00                           0.04
4   wrist_xray                     0.00                           0.00
..         ...                      ...                            ...
94  chest_xray                     0.00                           0.06
95     head_ct                     0.90                           0.00
96     head_ct                     0.45                           0.00
97  femur_xray                     0.00                           0.00
98  chest_xray                     0.00                           0.00

[99 rows x 3 columns]

In [7]:
total_prob = np.zeros(99)
worklist['total_prob']= total_prob
worklist

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,total_prob
0,chest_xray,0.00,0.05,0.0
1,chest_xray,0.00,0.17,0.0
2,chest_xray,0.00,0.00,0.0
3,chest_xray,0.00,0.04,0.0
4,wrist_xray,0.00,0.00,0.0
...,...,...,...,...
94,chest_xray,0.00,0.06,0.0
95,head_ct,0.90,0.00,0.0
96,head_ct,0.45,0.00,0.0
97,femur_xray,0.00,0.00,0.0
98,chest_xray,0.00,0.00,0.0

In [11]:
# create a new column by adding two probabilities
for index, row in worklist.iterrows():
#     row['total_prob'] = row['Brain_bleed_probability'] + row['Aortic_dissection_probability']
    total_prob[index] = row['Brain_bleed_probability'] + row['Aortic_dissection_probability']
#     print(row['total_prob'], row['Brain_bleed_probability'] + row['Aortic_dissection_probability'], row['Brain_bleed_probability'], row['Aortic_dissection_probability'])
#     worklist[index] = [row['Image_Type'], row['Brain_bleed_probability'], row['Aortic_dissection_probability'], row['total_prob']]

worklist['total_prob']= total_prob
worklist.head()

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,total_prob
0,chest_xray,0.0,0.05,0.05
1,chest_xray,0.0,0.17,0.17
2,chest_xray,0.0,0.00,0.00
3,chest_xray,0.0,0.04,0.04
4,wrist_xray,0.0,0.00,0.00

In [13]:
worklist.sort_values(by=['total_prob'], ascending=False)

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,total_prob
25,head_ct,0.99,0.00,0.99
15,chest_xray,0.00,0.95,0.95
10,chest_xray,0.00,0.94,0.94
75,chest_xray,0.00,0.93,0.93
47,chest_xray,0.00,0.93,0.93
...,...,...,...,...
73,femur_xray,0.00,0.00,0.00
37,chest_xray,0.00,0.00,0.00
35,wrist_xray,0.00,0.00,0.00
33,wrist_xray,0.00,0.00,0.00
98,chest_xray,0.00,0.00,0.00